version: "2.6"

services:
  client:
    image: 995353575805.dkr.ecr.eu-west-2.amazonaws.com/repository-organizer-client:latest
    build: ../client
    env_file:
      - ../client/.env
    ports:
      - 80:80
    volumes:
      - ./client:/usr/project/client:ro
    container_name: repository-organizer-client
    healthcheck:
      test: curl -f localhost:80/
      interval: 10s
      timeout: 10s
      retries: 1
    depends_on:
      server:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - back

  server:
    image: 995353575805.dkr.ecr.eu-west-2.amazonaws.com/repository-organizer-server:latest
    build: ../server
    env_file:
      - ../server/.env
    volumes:
      - ./server:/usr/project/server
    ports:
      - 4000:4000
    container_name: repository-organizer-server
    healthcheck:
      test: curl -f localhost:4000/healthy
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - back

networks:
  back:
    driver: bridge
