import typePrefixer from "../../utiles/typePrefixer";

const CURRENT_USER = "auth/CURRENT_USER";
const CURRENT_USER_SUCCESS = "auth/CURRENT_USER_SUCCESS";
const SIGNUP_USER = "auth/SIGNUP_USER";
const SIGNUP_USER_SUCCESS = "auth/SIGNUP_USER_SUCCESS";
const SIGNUP_USER_FAILED = "auth/SIGNUP_USER_FAILED";
const SIGNIN_USER = "auth/SIGNIN_USER";
const SIGNOUT_USER = "auth/SIGNOUT_USER";
const SIGNOUT_USER_SUCCESS = "auth/SIGNOUT_USER_SUCCESS";
const FETCH_FAILED = "auth/FETCH_FAILED";
const SHOW_NOTIFICATION = "auth/SHOW_NOTIFICATION";
const HIDE_NOTIFICATION = "auth/HIDE_NOTIFICATION";

const types = typePrefixer({
  CURRENT_USER,
  CURRENT_USER_SUCCESS,
  SIGNUP_USER,
  SIGNUP_USER_SUCCESS,
  SIGNUP_USER_FAILED,
  SIGNIN_USER,
  SIGNOUT_USER,
  SIGNOUT_USER_SUCCESS,
  FETCH_FAILED,
  SHOW_NOTIFICATION,
  HIDE_NOTIFICATION,
});

export default types;
